// <auto-generated />
namespace project_cripta.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.0")]
    public sealed partial class FixCreatedAtDefaultValue : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(FixCreatedAtDefaultValue));
        
        string IMigrationMetadata.Id
        {
            get { return "202511111313244_FixCreatedAtDefaultValue"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
